  import Head from 'next/head'
  import Link from 'next/link'
  import { useEffect, useState } from 'react'
  import { api } from '../../services/api'
  import styles from '../../styles/Home.module.css'
  import {useWebVitals} from '../../hooks/useWebVitals'


  const TIPO_DE_RENDERIZACAO = "CSR"

  export default function Home() {
    const [books,setBooks] = useState(null)

    useEffect(() => {
      async function fetchData() {
        const {data} = await api.get('/api/books');
        console.log(data)
        setBooks(data.results);
      }
      fetchData();
    }, []); 

    const {getMetrics}= useWebVitals()


    return (
      <div className={styles.container}>
        <Head>
          <title>Client-Side-Rendering</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Link href={"/"}>
            <a className={styles.initialPageLink}>
                Página Inicial
            </a>
        </Link>

        <main className={styles.main}>

          <h1 className={styles.title}>
            Modelo de Renderização: <a href="https://nextjs.org">{TIPO_DE_RENDERIZACAO}</a>
          </h1>

          <p className={styles.description}>
            Livros retirados de:  {" "}
            <strong>
              http://gutendex.com
            </strong>
          </p>


          <div className={styles.grid}>
            {books ? books.map(book => {
              return (
                <a key={book.id} href="https://nextjs.org/docs" className={styles.card}>
                  <h2>{book.title}</h2>
                  <img src={book.formats["image/jpeg"]} alt={book.title}/>
                  <p>{book.authors.map(author => author.name ).join(' ')}</p>
                </a>
              )
            }): `Carregando...`}
            
          </div>
        </main>

        <footer className={styles.footer}>
          Pattern - {TIPO_DE_RENDERIZACAO}

          <button type="" onClick={() => getMetrics()}>Métricas</button>
        </footer>
      </div>
    )
  }
