  import Head from 'next/head'
  import Link from 'next/link'
  import styles from '../styles/Home.module.css'

  export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Modelos de Renderização com Next.js</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Modelos de renderização
          </h1>

          <p className={styles.description}>
            Projeto exemplificando listagem de livros <br/> em diferentes modelos de renderização
          </p>

          <div className={styles.grid}>
            <Link href="/client-side-rendering">
              <a className={styles.card}>
              <h2>CSR &rarr;</h2>
              <p>Exemplo de Client Side Rendering ou Renderização no lado do cliente.</p>
              </a>
            </Link>

            <Link href="/server-side-rendering"    >
              <a className={styles.card}>
                <h2>SSR &rarr;</h2>
                <p>Exemplo de Server Side Rendering ou Renderização no lado do servidor.</p>
              </a>
            </Link>

            <Link
              href="/static-generation"
            >
              <a className={styles.card}>
                <h2>SSG &rarr;</h2>
                <p>Exemplo de Static Site Renderização ou Renderização de sites estáticos. </p>
              </a>
            </Link>
          </div>
        </main>

        <footer className={styles.footer}>
          Projeto desenvolvido por Fabrício Ziliotti
        </footer>
      </div>
    )
  }
